### ISSUE TITLE
Quote Aliases

### ISSUE THREAD

**Issue by KeyboardCowboy** [KeyboardCowboy/drush-denver#27]
Drush aliases use the `@`, which is protected in YAML parsing.  The tests included in this package contain unquoted aliases.  These need to be quoted to prevent the following error:

```
exception 'Symfony\Component\Yaml\Exception\ParseException' with message 'The reserved indicator "@" cannot start a plain scalar; you need to quote the scalar at line 11 (near "alias: @test").' in /app/vendor/symfony/yaml/Inline.php:353         [error]
Stack trace:
#0 /app/vendor/symfony/yaml/Inline.php(125): Symfony\Component\Yaml\Inline::parseScalar('@test', 0, NULL, 5, true, Array)
#1 /app/vendor/symfony/yaml/Parser.php(783): Symfony\Component\Yaml\Inline::parse('@test', 0, Array)
#2 /app/vendor/symfony/yaml/Parser.php(387): Symfony\Component\Yaml\Parser->parseValue('@test', 0, 'mapping')
#3 /app/vendor/symfony/yaml/Parser.php(504): Symfony\Component\Yaml\Parser->doParse('alias: @test\nar...', 0)
#4 /app/vendor/symfony/yaml/Parser.php(365): Symfony\Component\Yaml\Parser->parseBlock(10, 'alias: @test\nar...', 0)
#5 /app/vendor/symfony/yaml/Parser.php(504): Symfony\Component\Yaml\Parser->doParse('# Longform synt...', 0)
#6 /app/vendor/symfony/yaml/Parser.php(365): Symfony\Component\Yaml\Parser->parseBlock(8, '# Longform synt...', 0)
#7 /app/vendor/symfony/yaml/Parser.php(141): Symfony\Component\Yaml\Parser->doParse('modules:\n  enab...', 0)
#8 /app/vendor/symfony/yaml/Yaml.php(111): Symfony\Component\Yaml\Parser->parse('modules:\n  enab...', 0)
#9 /app/docroot/sites/all/drush/commands/drush-denver/Denver.class.php(672): Symfony\Component\Yaml\Yaml::parse('modules:\n  enab...')
#10 /app/docroot/sites/all/drush/commands/drush-denver/Denver.class.php(654): Denver->extractEnv('/app/docroot/si...')
#11 /app/docroot/sites/all/drush/commands/drush-denver/Denver.class.php(639): Denver->loadEnvFile(Object(stdClass))
#12 /app/docroot/sites/all/drush/commands/drush-denver/Denver.class.php(49): Denver->findEnvironments()
#13 /app/docroot/sites/all/drush/commands/drush-denver/environment.drush.inc(67): Denver->__construct()
#14 [internal function]: drush_environment('reset')
#15 /app/vendor/drush/drush/includes/command.inc(422): call_user_func_array('drush_environme...', Array)
#16 /app/vendor/drush/drush/includes/command.inc(231): _drush_invoke_hooks(Array, Array)
#17 [internal function]: drush_command('reset')
#18 /app/vendor/drush/drush/includes/command.inc(199): call_user_func_array('drush_command', Array)
#19 /app/vendor/drush/drush/lib/Drush/Boot/BaseBoot.php(67): drush_dispatch(Array)
#20 /app/vendor/drush/drush/includes/preflight.inc(66): Drush\Boot\BaseBoot->bootstrap_and_dispatch()
#21 /app/vendor/drush/drush/drush.php(12): drush_main()
#22 {main}
```

**Comment by KeyboardCowboy** [comment]
Resolved in tag 2.2.3.
